name: Tutorial
author: MariusLange
version: 1.0

main: me.mariuslange.tutorial.Tutorial

commands:
  tutorial:
    description: Dies ist der Tutorial-Befehl
    usage: /<command>
  info:
    description: Info ueber dich
    usage: /<command>